[platformio]
src_dir = esp32_firmware_modular
data_dir = data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
monitor_speed = 115200